language: node_js
node_js:
- '8'
cache:
  directories:
  - "$HOME/.npm"
  before_install:
  - npm i -g discord.js@11.1.0
before_install:
- openssl aes-256-cbc -K $encrypted_f7e97528a2c7_key -iv $encrypted_f7e97528a2c7_iv
  -in config.json.enc -out config.json -d
